spring.application.name=Ticketapp
server.port = 8080

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ticket_booking_db?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=mysqlpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# PayHere Configuration
payhere.merchant.id=1236166
payhere.merchant.secret=MTE1ODE2MDQ1OTM0MTQwODI0NjE3ODExMDg3NTUzODQ2ODczNDE2
payhere.currency=LKR

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akilaisurukahingala@gmail.com
spring.mail.password=vfqzrgczrjfjxtjj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true